### ISSUE TITLE
Experience gain on load.

### ISSUE THREAD

**Issue by cokemonsterps3** [DegenDomain/LolilithsThroneIssueTracker#11] opened 2023-07-20 06:03 UTC
**Describe the bug**
Experience gain on reload.

**To Reproduce**

1. Resume/Load a save

2. Gain EXP from a fight and head home to sleep, causing an autosave

3. Immediately loading the autosave to find just about double the level gained.

![Capture](https://github.com/DegenDomain/LolilithsThroneIssueTracker/assets/140046381/b7bb7b49-df8b-44fc-b06a-601c7191a143)

**Additional context**
No I don't believe it is fixed. I threw the hotfix jar into the Rewrite folder of the previous R17 copy doing nothing else to the data or res folders. I did the exact same thing in the R17 and R17_1. I am playing on the Lilin difficulty and haven't touched any mod option multipliers. Goodluck with whatever the hell this is o7.

**Comment by DrakeFaewylde** [comment] 2023-07-20 12:41
Released [Hotfix 2](https://github.com/DegenDomain/LolilithsThroneIssueTracker/releases/tag/R17Hotfix2) as a temporary solution to this issue.

As a partial workaround, and because it was something that probably should have been done much sooner, the debug menu now allows you to increment level and reset level instead of +500 xp (player) and +500 xp (main companion)

The code specifically targets the player and each companion and increases their level by 1; and the reset checks their current level, then reduces them to `getLevel() - 1` so it should have no issues as a workaround for this problem. Though it will require a few extra clicks to get those first couple dozen levels, it should give more control to players in the short and long term.

In the future I plan to expand on this system and make a new page specifically for managing the party's level, and I hope to expand on that further once it's working as intended... but that's extremely low priority as compared to other things in the project.

**Comment by abrisinski** [comment] 2023-07-25 08:19
You might've already figured it out, but if not I wanted to mention that it seems the issue is to do with max EXP not updating properly when loaded. It seems stuck at 10?

Every time I gain 10 experience, that converts precisely into 1 level when the file is reloaded. This can be demonstrated by editing the save file directly: change your player's experience value to any number, say 294, and you'll find you gain +29 levels and have 4 experience leftover when you reload the file.

**Comment by DrakeFaewylde** [comment] 2023-07-25 13:28
I had not figured it out, so I absolutely appreciate the information. I've added some debug stuff behind the scenes (will not affect performance moving forward) to help identify the issue, but my current theory is that the game is not actually applying the current level (and by extension the experience required to level up) until after the experience has been added.

For clarify, here's how it should work:
~ Game starts
~ Press load/continue
~ loading begins
~~ check level
~~ update level
~~ check experience
~~ update experience
~ load everything else

And here's how it is actually working:
~ Game starts
~ Press load/continue
~ loading begins
~~ check level
~~ check experience
~~ update experience
~~ update level
~ load everything else

The first and only potential cause I can think of is the multithreading, since it seems to read and write data at incorrect intervals, it's like it's loading all the data at once, then applying changes out of order... but the multithreading is entirely DrZed's domain. I'll add him to this bug because I highly doubt I can solve this problem.

Here's a little extra information to help @DrZed along...
Load function: 
GameCharacter.java:1205 (Search `/* TODO Remove this later */` for all instances)
Actual data being loaded from xml:
game → playerCharacter → character → level
game → playerCharacter → character → experience

**Comment by RisenBlade** [comment] 2023-08-10 07:42
wow
![Новый точечный рисунок](https://github.com/DegenDomain/LolilithsThroneIssueTracker/assets/56949745/de0cf121-50ab-40c1-86a5-413ba7aca712)

**Comment by Rsslone** [comment] 2023-08-14 04:47
I just encountered this bug, the xp doesn't apply the level up correctly. I'm seeing something such as 610/580 xp, the top exp bar overruns its intended area, and on a reload of the game, my character level jumps from 60 to 120.

**Comment by DrZed** [comment] 2023-08-15 03:05
Out of curiousity do you have the setting for XP Multiplier turned up above 100%?

**Comment by Rsslone** [comment] 2023-08-15 05:30
No, its at default 100%. I didn't have this issue early on for some reason, could it have something to do with the difficulty setting? That's one setting I did change later on in the playthrough.

**Comment by DrakeFaewylde** [comment] 2023-08-15 20:34
At level 1 you need 10 experience to level up, and since you had 269 experience it added 26 levels, then added the other 9 levels.

Refer to my previous message for why this is happening.

**Comment by Rsslone** [comment] 2023-08-17 09:11
Just reporting back that this is fixed in R18.1

Thank you for everything you do!

**Closed** 2023-08-18 01:42 UTC
Labels: bug
